package io.imking.common.mapping;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import io.imking.common.domain.Attachment;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @Delete({
        "delete from t_attachment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @Insert({
        "insert into t_attachment (id, file_name, ",
        "path, size, file_type, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{fileName,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=VARCHAR}, #{size,jdbcType=BIGINT}, #{fileType,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @InsertProvider(type=AttachmentSqlProvider.class, method="insertSelective")
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @Select({
        "select",
        "id, file_name, path, size, file_type, create_time",
        "from t_attachment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="file_name", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="path", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="size", property="size", jdbcType=JdbcType.BIGINT),
        @Result(column="file_type", property="fileType", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    Attachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @UpdateProvider(type=AttachmentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    @Update({
        "update t_attachment",
        "set file_name = #{fileName,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "size = #{size,jdbcType=BIGINT},",
          "file_type = #{fileType,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Attachment record);
}