package io.imking.common.domain;

import java.util.Date;

public class Attachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.id
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.file_name
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.path
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.size
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.file_type
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attachment.create_time
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.id
     *
     * @return the value of t_attachment.id
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.id
     *
     * @param id the value for t_attachment.id
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.file_name
     *
     * @return the value of t_attachment.file_name
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.file_name
     *
     * @param fileName the value for t_attachment.file_name
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.path
     *
     * @return the value of t_attachment.path
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.path
     *
     * @param path the value for t_attachment.path
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.size
     *
     * @return the value of t_attachment.size
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.size
     *
     * @param size the value for t_attachment.size
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.file_type
     *
     * @return the value of t_attachment.file_type
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.file_type
     *
     * @param fileType the value for t_attachment.file_type
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attachment.create_time
     *
     * @return the value of t_attachment.create_time
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attachment.create_time
     *
     * @param createTime the value for t_attachment.create_time
     *
     * @mbg.generated Wed Jan 24 11:10:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}