package io.imking.biz.domain;

import java.util.Date;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_business.business_name
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private String businessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_business.state
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_business.create_time
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_business.id
     *
     * @return the value of tc_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_business.id
     *
     * @param id the value for tc_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_business.business_name
     *
     * @return the value of tc_business.business_name
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_business.business_name
     *
     * @param businessName the value for tc_business.business_name
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_business.state
     *
     * @return the value of tc_business.state
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_business.state
     *
     * @param state the value for tc_business.state
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_business.create_time
     *
     * @return the value of tc_business.create_time
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_business.create_time
     *
     * @param createTime the value for tc_business.create_time
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}