package io.imking.biz.domain;

public class CustBusiness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_business.cust_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_business.biz_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    private Long bizId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_business.id
     *
     * @return the value of tc_cust_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_business.id
     *
     * @param id the value for tc_cust_business.id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_business.cust_id
     *
     * @return the value of tc_cust_business.cust_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_business.cust_id
     *
     * @param custId the value for tc_cust_business.cust_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_business.biz_id
     *
     * @return the value of tc_cust_business.biz_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public Long getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_business.biz_id
     *
     * @param bizId the value for tc_cust_business.biz_id
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public void setBizId(Long bizId) {
        this.bizId = bizId;
    }
}