package io.imking.biz.domain;

import java.util.Date;

public class CustInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.id
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.cust_name
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.wechat
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.qq
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.cc_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String ccTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.email
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.phone
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_cust_info.create_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.id
     *
     * @return the value of tc_cust_info.id
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.id
     *
     * @param id the value for tc_cust_info.id
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.cust_name
     *
     * @return the value of tc_cust_info.cust_name
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.cust_name
     *
     * @param custName the value for tc_cust_info.cust_name
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.wechat
     *
     * @return the value of tc_cust_info.wechat
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.wechat
     *
     * @param wechat the value for tc_cust_info.wechat
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.qq
     *
     * @return the value of tc_cust_info.qq
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.qq
     *
     * @param qq the value for tc_cust_info.qq
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.cc_time
     *
     * @return the value of tc_cust_info.cc_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getCcTime() {
        return ccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.cc_time
     *
     * @param ccTime the value for tc_cust_info.cc_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setCcTime(String ccTime) {
        this.ccTime = ccTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.email
     *
     * @return the value of tc_cust_info.email
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.email
     *
     * @param email the value for tc_cust_info.email
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.phone
     *
     * @return the value of tc_cust_info.phone
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.phone
     *
     * @param phone the value for tc_cust_info.phone
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_cust_info.create_time
     *
     * @return the value of tc_cust_info.create_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_cust_info.create_time
     *
     * @param createTime the value for tc_cust_info.create_time
     *
     * @mbg.generated Fri Jan 19 10:30:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}