package edu.ldcollege.mapping;

import edu.ldcollege.domain.TBClassUser;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TBClassUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_class_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_class_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_class_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_class_user (id, userName, ",
        "classId, userType, ",
        "userStatus)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{classid,jdbcType=INTEGER}, #{usertype,jdbcType=TINYINT}, ",
        "#{userstatus,jdbcType=TINYINT})"
    })
    int insert(TBClassUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_class_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, classId, userType, userStatus",
        "from tbl_class_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="userType", property="usertype", jdbcType=JdbcType.TINYINT),
        @Result(column="userStatus", property="userstatus", jdbcType=JdbcType.TINYINT)
    })
    TBClassUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_class_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, classId, userType, userStatus",
        "from tbl_class_user"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="userType", property="usertype", jdbcType=JdbcType.TINYINT),
        @Result(column="userStatus", property="userstatus", jdbcType=JdbcType.TINYINT)
    })
    List<TBClassUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_class_user
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_class_user",
        "set userName = #{username,jdbcType=VARCHAR},",
          "classId = #{classid,jdbcType=INTEGER},",
          "userType = #{usertype,jdbcType=TINYINT},",
          "userStatus = #{userstatus,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBClassUser record);
}