package edu.ldcollege.mapping;

import edu.ldcollege.domain.TBCourse;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TBCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_course
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tbl_course",
        "where cId = #{cid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_course
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tbl_course (cId, classId, ",
        "name, description)",
        "values (#{cid,jdbcType=INTEGER}, #{classid,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})"
    })
    int insert(TBCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_course
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "cId, classId, name, description",
        "from tbl_course",
        "where cId = #{cid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cId", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    TBCourse selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_course
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "cId, classId, name, description",
        "from tbl_course"
    })
    @Results({
        @Result(column="cId", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<TBCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_course
     *
     * @mbg.generated
     */
    @Update({
        "update tbl_course",
        "set classId = #{classid,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where cId = #{cid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBCourse record);
}