package edu.ldcollege.mapping;

import java.util.List;
import edu.ldcollege.domain.TBMemu;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TBMemuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_menu (id, menuName, ",
        "hint, order)",
        "values (#{id,jdbcType=INTEGER}, #{menuname,jdbcType=VARCHAR}, ",
        "#{hint,jdbcType=VARCHAR}, #{order,jdbcType=TINYINT})"
    })
    int insert(TBMemu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, menuName, hint, order",
        "from t_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menuName", property="menuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="hint", property="hint", jdbcType=JdbcType.VARCHAR),
        @Result(column="order", property="order", jdbcType=JdbcType.TINYINT)
    })
    TBMemu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, menuName, hint, order",
        "from t_menu"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menuName", property="menuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="hint", property="hint", jdbcType=JdbcType.VARCHAR),
        @Result(column="order", property="order", jdbcType=JdbcType.TINYINT)
    })
    List<TBMemu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated
     */
    @Update({
        "update t_menu",
        "set menuName = #{menuname,jdbcType=VARCHAR},",
          "hint = #{hint,jdbcType=VARCHAR},",
          "order = #{order,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBMemu record);
    
    
    /**
     * 查询用户面板
     * @param username 用户名
     * @return
     */
    @Select({
    	"select",
    	"m.*",
    	"from t_user2menu as um inner join t_menu as m on um.id = m.menuId",
    	"where um.userName = #{username,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menuName", property="menuname", jdbcType=JdbcType.VARCHAR),
        @Result(column="hint", property="hint", jdbcType=JdbcType.VARCHAR),
        @Result(column="order", property="order", jdbcType=JdbcType.TINYINT)
    })
    List<TBMemu> selectUserMenus(@Param("username") String username);
    
    
}