package edu.ldcollege.mapping;

import java.util.List;
import edu.ldcollege.domain.TBUser2Memu;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TBUser2MemuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user2menu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_user2menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user2menu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_user2menu (id, userName, ",
        "menuId)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{menuid,jdbcType=INTEGER})"
    })
    int insert(TBUser2Memu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user2menu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, menuId",
        "from t_user2menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="menuId", property="menuid", jdbcType=JdbcType.INTEGER)
    })
    TBUser2Memu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user2menu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, menuId",
        "from t_user2menu"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="menuId", property="menuid", jdbcType=JdbcType.INTEGER)
    })
    List<TBUser2Memu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user2menu
     *
     * @mbg.generated
     */
    @Update({
        "update t_user2menu",
        "set userName = #{username,jdbcType=VARCHAR},",
          "menuId = #{menuid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TBUser2Memu record);
}