package edu.ldcollege.domain;

import java.util.Date;

public class TBLdClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.classId
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.className
     *
     * @mbg.generated
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.classDesc
     *
     * @mbg.generated
     */
    private String classdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.createDay
     *
     * @mbg.generated
     */
    private Date createday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.startDate
     *
     * @mbg.generated
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.endDay
     *
     * @mbg.generated
     */
    private Date endday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.monitorId
     *
     * @mbg.generated
     */
    private Integer monitorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.commissaryId
     *
     * @mbg.generated
     */
    private Integer commissaryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.curNormalStudents
     *
     * @mbg.generated
     */
    private Integer curnormalstudents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.curArrearagedStudents
     *
     * @mbg.generated
     */
    private Integer curarrearagedstudents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldclass.dropedStudents
     *
     * @mbg.generated
     */
    private Integer dropedstudents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.classId
     *
     * @return the value of ldclass.classId
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.classId
     *
     * @param classid the value for ldclass.classId
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.className
     *
     * @return the value of ldclass.className
     *
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.className
     *
     * @param classname the value for ldclass.className
     *
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.classDesc
     *
     * @return the value of ldclass.classDesc
     *
     * @mbg.generated
     */
    public String getClassdesc() {
        return classdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.classDesc
     *
     * @param classdesc the value for ldclass.classDesc
     *
     * @mbg.generated
     */
    public void setClassdesc(String classdesc) {
        this.classdesc = classdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.createDay
     *
     * @return the value of ldclass.createDay
     *
     * @mbg.generated
     */
    public Date getCreateday() {
        return createday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.createDay
     *
     * @param createday the value for ldclass.createDay
     *
     * @mbg.generated
     */
    public void setCreateday(Date createday) {
        this.createday = createday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.startDate
     *
     * @return the value of ldclass.startDate
     *
     * @mbg.generated
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.startDate
     *
     * @param startdate the value for ldclass.startDate
     *
     * @mbg.generated
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.endDay
     *
     * @return the value of ldclass.endDay
     *
     * @mbg.generated
     */
    public Date getEndday() {
        return endday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.endDay
     *
     * @param endday the value for ldclass.endDay
     *
     * @mbg.generated
     */
    public void setEndday(Date endday) {
        this.endday = endday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.monitorId
     *
     * @return the value of ldclass.monitorId
     *
     * @mbg.generated
     */
    public Integer getMonitorid() {
        return monitorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.monitorId
     *
     * @param monitorid the value for ldclass.monitorId
     *
     * @mbg.generated
     */
    public void setMonitorid(Integer monitorid) {
        this.monitorid = monitorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.commissaryId
     *
     * @return the value of ldclass.commissaryId
     *
     * @mbg.generated
     */
    public Integer getCommissaryid() {
        return commissaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.commissaryId
     *
     * @param commissaryid the value for ldclass.commissaryId
     *
     * @mbg.generated
     */
    public void setCommissaryid(Integer commissaryid) {
        this.commissaryid = commissaryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.curNormalStudents
     *
     * @return the value of ldclass.curNormalStudents
     *
     * @mbg.generated
     */
    public Integer getCurnormalstudents() {
        return curnormalstudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.curNormalStudents
     *
     * @param curnormalstudents the value for ldclass.curNormalStudents
     *
     * @mbg.generated
     */
    public void setCurnormalstudents(Integer curnormalstudents) {
        this.curnormalstudents = curnormalstudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.curArrearagedStudents
     *
     * @return the value of ldclass.curArrearagedStudents
     *
     * @mbg.generated
     */
    public Integer getCurarrearagedstudents() {
        return curarrearagedstudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.curArrearagedStudents
     *
     * @param curarrearagedstudents the value for ldclass.curArrearagedStudents
     *
     * @mbg.generated
     */
    public void setCurarrearagedstudents(Integer curarrearagedstudents) {
        this.curarrearagedstudents = curarrearagedstudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldclass.dropedStudents
     *
     * @return the value of ldclass.dropedStudents
     *
     * @mbg.generated
     */
    public Integer getDropedstudents() {
        return dropedstudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldclass.dropedStudents
     *
     * @param dropedstudents the value for ldclass.dropedStudents
     *
     * @mbg.generated
     */
    public void setDropedstudents(Integer dropedstudents) {
        this.dropedstudents = dropedstudents;
    }
}