package edu.ldcollege.domain;

public class TBUser2Memu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user2menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user2menu.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user2menu.menuId
     *
     * @mbg.generated
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user2menu.id
     *
     * @return the value of t_user2menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user2menu.id
     *
     * @param id the value for t_user2menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user2menu.userName
     *
     * @return the value of t_user2menu.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user2menu.userName
     *
     * @param username the value for t_user2menu.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user2menu.menuId
     *
     * @return the value of t_user2menu.menuId
     *
     * @mbg.generated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user2menu.menuId
     *
     * @param menuid the value for t_user2menu.menuId
     *
     * @mbg.generated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}