package io.imking.biz.mapping;

import io.imking.biz.domain.Business;
import org.apache.ibatis.jdbc.SQL;

public class BusinessSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_business
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String insertSelective(Business record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tc_business");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getBusinessName() != null) {
            sql.VALUES("business_name", "#{businessName,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            sql.VALUES("state", "#{state,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_business
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String updateByPrimaryKeySelective(Business record) {
        SQL sql = new SQL();
        sql.UPDATE("tc_business");
        
        if (record.getBusinessName() != null) {
            sql.SET("business_name = #{businessName,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            sql.SET("state = #{state,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}