package io.imking.biz.mapping;

import io.imking.biz.domain.CustBusiness;
import org.apache.ibatis.jdbc.SQL;

public class CustBusinessSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_cust_business
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String insertSelective(CustBusiness record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tc_cust_business");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getCustId() != null) {
            sql.VALUES("cust_id", "#{custId,jdbcType=BIGINT}");
        }
        
        if (record.getBizId() != null) {
            sql.VALUES("biz_id", "#{bizId,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_cust_business
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String updateByPrimaryKeySelective(CustBusiness record) {
        SQL sql = new SQL();
        sql.UPDATE("tc_cust_business");
        
        if (record.getCustId() != null) {
            sql.SET("cust_id = #{custId,jdbcType=BIGINT}");
        }
        
        if (record.getBizId() != null) {
            sql.SET("biz_id = #{bizId,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}