package io.imking.biz.mapping;

import io.imking.biz.domain.CustInfo;
import org.apache.ibatis.jdbc.SQL;

public class CustInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_cust_info
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String insertSelective(CustInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tc_cust_info");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getCustName() != null) {
            sql.VALUES("cust_name", "#{custName,jdbcType=VARCHAR}");
        }
        
        if (record.getWechat() != null) {
            sql.VALUES("wechat", "#{wechat,jdbcType=VARCHAR}");
        }
        
        if (record.getQq() != null) {
            sql.VALUES("qq", "#{qq,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_cust_info
     *
     * @mbg.generated Wed Jan 17 21:46:14 CST 2018
     */
    public String updateByPrimaryKeySelective(CustInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("tc_cust_info");
        
        if (record.getCustName() != null) {
            sql.SET("cust_name = #{custName,jdbcType=VARCHAR}");
        }
        
        if (record.getWechat() != null) {
            sql.SET("wechat = #{wechat,jdbcType=VARCHAR}");
        }
        
        if (record.getQq() != null) {
            sql.SET("qq = #{qq,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}